name: your_app_name
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Video Editing & Playback
  video_player: ^2.8.2
  video_compress: ^4.1.0
  ffmpeg_kit_flutter: ^5.1.0
  chewie: ^1.5.0  # Enhanced video player
  
  # File & Storage
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  
  # State Management & Utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # UI Enhancements
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Date & Time
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

 