name: signsync_academy
description: A South African Sign Language e-learning platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.1.2
  flutter_dotenv: ^5.1.0
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master
  image_picker: ^1.1.2
  path: ^1.8.3
  mime: ^1.0.5
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  chewie: ^1.7.2  # For better video controls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true